import type { TalkItem, CommunityItem, SocialLink, CommandDefinition, ProjectItem } from "./types";

export const TALKS: TalkItem[] = [
  {
    id: "stratum-2026-ai-in-practice",
    index: "01",
    title: "Speaking on AI in Practice: AI Integration & Data (SYNAPSE)",
    event: "Stratum 2026: Career Guidance Seminar — Finding Your Ground in the CpE Landscape",
    date: "May 13, 2026",
    venue: "CEA Room 315, PUP Manila, Philippines",
    topic: "Utilitarian AI architectures, backend systems, automation, clean functional system design, and bridging the gap between complex technical infrastructure and real-world business needs",
    impact: "Featured Day 2 speaker representing Accenture and PUP CpE alumni; delivering 'SYNAPSE: AI Integration & Data', providing utilitarian architectural frameworks and career mentorship for computer engineering students.",
    image: "/stratum-2026-ai-in-practice.jpg",
    imageAlt: "Engr. Marvin James Erosa featured speaker poster at Stratum 2026 on AI in Practice: AI Integration & Data (SYNAPSE)",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/1QG82R9Qub/" },
    ],
  },
  {
    id: "zero-to-agent-manila",
    index: "02",
    title: "From Zero to v0: Turning Ideas into Working Prototypes",
    event: "Vercel Global Build Week — Zero to Agent: Manila",
    date: "April 25, 2026",
    venue: "LEAP Studios, Manila, Philippines",
    topic: "Building working prototypes with v0 by Vercel at a day of lightning talks, mini-hackathon & community networking",
    impact: "Representing the Philippines in Vercel's Global Build Week as v0 Ambassador; delivering a lightning talk on turning ideas into working prototypes with v0 alongside co-speaker Werald Opolento, hosted by LEAP Studios with SerpApi (Platinum), Rotary Club of Fort Bonifacio Global City (Silver), swarm (Bronze), AWS User Groups Philippines (e:Novators), and Data Engineering Pilipinas.",
    image: "/zero-to-agent-manila.jpg",
    imageAlt: "Zero to Agent: Manila — Vercel Global Build Week agenda and speaker lineup featuring Marvin Erosa (v0 Ambassador)",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/1DCCBBGYMh/" },
    ],
  },
  {
    id: "aws-concept-to-connection-2026",
    index: "03",
    title: "From Concept to Connection: Bridging Embedded Systems & Cloud",
    event: "AWS Cloud Club PUP — IoT Workshop: From Concept to Connection",
    date: "January 27, 2026",
    venue: "AWS Office, 21F Arthaland Century Pacific Tower, BGC, Taguig",
    topic: "Connecting physical hardware to cloud infrastructure, embedded sensors, and solving real-world challenges where hardware and software collide",
    impact: "Featured speaker at AWS Philippines HQ; mentored student engineers on open-source hardware integration, IoT sensor telemetry, and cloud workflows alongside Daniel Cosare.",
    image: "/aws-concept-to-connection-2026.jpg",
    imageAlt: "AWS Cloud Club PUP speaker spotlight — Marvin James Erosa (Co-Organizer of ADPH | Embedded Systems Expert)",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/19cTyuV5dQ/" },
    ],
  },
  {
    id: "dost-techstart-2025",
    index: "04",
    title: "TechSTART: Tech the Halls — An IoT Holiday Jam",
    event: "DOST START — TechSTART: Ohms for the Holidays",
    date: "December 22, 2025",
    venue: "Virtual (Zoom Meeting)",
    topic: "Demystifying embedded systems, Arduino architecture, IoT sensor networks, and open-source hardware integration",
    impact: "Featured speaker representing Arduino Day Philippines; trained nationwide DOST scholar-engineers on IoT prototyping, microcontroller design, and open-source hardware best practices.",
    image: "/dost-techstart-2025.jpg",
    imageAlt: "DOST TechSTART speaker poster — Marvin James A. Erosa on Tech the Halls: An IoT Holiday Jam",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/17XeSk37kz/" },
    ],
  },
  {
    id: "commits-general-assembly-2025",
    index: "05",
    title: "How to Break Your Own AI",
    event: "CommITs General Assembly 2025 — Link & Lead: Virus Infect, Leaders Connect",
    date: "December 12, 2025",
    venue: "PUP Quezon City, Philippines",
    topic: "AI vulnerabilities, adversarial testing, red-teaming methodologies, and security architectures for intelligent systems",
    impact: "Featured seminar speaker representing GDG Alumni; delivered a highly engaging session on 'How to Break Your Own AI', guiding IT students through AI security vulnerabilities and practical defenses.",
    image: "/commits-general-assembly-2025.jpg",
    imageAlt: "Marvin James Erosa speaking on stage at CommITs General Assembly 2025: Link & Lead",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/1FXcQ1omxM/" },
    ],
  },
  {
    id: "campus-devcon-manila-2025",
    index: "06",
    title: "How to Break Your Own AI",
    event: "Campus DEVCON Manila 2025 — Unlocking Cyber Defense",
    date: "November 24, 2025",
    venue: "TUP-Manila – IRTC Conference Hall",
    topic: "Ethical hacking, red-teaming strategies, and stress-testing AI systems to uncover vulnerabilities and safeguard intelligent applications",
    impact: "Featured speaker representing CyberPH; equipped developers and students with red-teaming methodologies, attack vectors, and defense frameworks to secure production AI systems.",
    image: "/campus-devcon-manila-2025.jpg",
    imageAlt: "Campus DEVCON Manila 2025 speaker banner — Marvin James Erosa (VP for Strategic Planning, CyberPH) on How to Break Your Own AI",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/p/1HQk7TPG6N/" },
    ],
  },
  {
    id: "phsw25-jailbreaking-ai",
    index: "07",
    title: "Jailbreaking Your Own AI (Before Someone Else Does): A Founder's Guide",
    event: "Philippine Startup Week 2025 — Scaling Filipino Innovation",
    date: "November 14, 2025",
    venue: "Abaca Room, M4 Mezzanine, Manila, Philippines",
    topic: "Adversarial testing, prompt injection, LLM jailbreak defense, and robust AI security architectures for startup founders",
    impact: "Led an intensive 4-hour hands-on workshop representing CyberPH at the country's premier national startup conference, training startup founders and engineering teams on safeguarding production AI applications against emerging cyber threats.",
    image: "/ph-startup-week-2025.jpg",
    imageAlt: "Marvin James Erosa at Philippine Startup Week 2025 representing CyberPH",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/LearnCyberPH/posts/pfbid02Sp26YYQrH7CYtBQ3JviJYTFW6L7QoQdkJknvcEbhSsJ6neusXaLE7UWmYzW3DeNEl" },
    ],
  },
  {
    id: "cpeyesta-2025",
    index: "08",
    title: "Your Tools Are Key: Hardware Engineering, Diagnostics & Instrumentation",
    event: "ICpEP.SE NCR — CPEYESTA 2025",
    date: "November 13, 2025",
    venue: "Philippine Christian University, Manila, Philippines",
    topic: "Hardware diagnostics, electronic test equipment, multimeter mastery, and practical engineering tooling for computer engineering students",
    impact: "Invited speaker on stage representing PUP Manila and ICpEP.SE; demonstrated hands-on diagnostic workflows and essential test equipment mastery ('Your Tools Are Key') to regional computer engineering students across affiliated NCR universities.",
    image: "/cpeyesta-2025.jpg",
    imageAlt: "Marvin James Erosa presenting 'Your Tools Are Key' on stage holding diagnostic hardware at CPEYESTA 2025",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/1DryhFqJ2Q/" },
    ],
  },
  {
    id: "icpep-ready-to-deploy",
    index: "09",
    title: "Ready to Deploy: Competitive Programming & Technical Mastery",
    event: "ICpEP SE PUP Manila — Ready to Deploy (Day 3: Programming)",
    date: "February 2025",
    venue: "PUP Manila, Philippines",
    topic: "Competitive programming strategies, algorithm design, technical problem solving, and quiz bowl mastery for computer engineering students",
    impact: "Featured Day 3 speaker alongside Engr. Kyne Domerei Laggui; mentored student engineers on competitive programming problem-solving and algorithms for the CPE Challenge as Founding President of ICpEP SE PUP Manila.",
    image: "/icpep-ready-to-deploy.jpg",
    imageAlt: "ICpEP Student Edition PUP Manila — Ready to Deploy Day 3 Programming Speakers: Engr. Marvin James Erosa and Engr. Kyne Domerei Laggui",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/share/1EPD398Lmp/" },
    ],
  },
  {
    id: "commits-general-assembly-2024",
    index: "10",
    title: "Navigating the Evolving Landscape of Cybersecurity",
    event: "CommITs General Assembly — Start-Up: The First Line of Code",
    date: "November 27, 2024",
    venue: "PUP Quezon City, Philippines",
    topic: "Comprehensive cybersecurity overview, real-world threat landscapes, defensive engineering, and hands-on CTF methodologies",
    impact: "Featured speaker representing Google Developer Group on Campus PUP; introduced IT students to security fundamentals, adversarial testing, and competitive Capture The Flag frameworks.",
    image: "/commits-general-assembly-2024.jpg",
    imageAlt: "Marvin James Erosa featured speaker poster at CommITs General Assembly — Start-Up: The First Line of Code",
    links: [
      { label: "Announcement Post", url: "https://www.facebook.com/CommITSPUPQC/posts/pfbid03ahJMT9SQx31aYkzdGxAyQd88K92xm4yGGJwSwK6FZc85WdihiRMJnvRCb4JccHnl" },
    ],
  },
];

export const COMMUNITY: CommunityItem[] = [
  {
    id: "arduino-day-ph",
    index: "01",
    title: "Arduino Day Philippines",
    role: "Co-Chair",
    period: "Nov. 2024 – Present",
    location: "Taguig / Manila, Philippines",
    description:
      "Directing end-to-end event operations, town planning, and strategic communications for a premier 2,000+ attendee maker conference. Leading cross-functional teams across marketing, logistics, and sponsorships, while overseeing the technical architecture of the official Next.js registration portal processing 2,500+ sign-ups.",
    impact: "Spearheaded 2,000+ attendee premier national maker conference with 2,500+ registrations on custom Next.js portal.",
    image: "/arduino-day-philippines.JPG",
    imageAlt: "Arduino Day Philippines national maker conference",
    tags: ["Next.js", "Event Operations", "Hardware & IoT", "Sponsorships"],
  },
  {
    id: "cyberph",
    index: "02",
    title: "CyberPH",
    role: "Co-Founder, VP for Strategic Planning & VP for Technology",
    period: "Apr. 2025 – Present",
    location: "Philippines",
    description:
      "Co-founded the organization and shaped its strategic roadmap, defining executive policies and key industry partnerships (e.g., PLDT Innolabs). Built the official CyberPH website, engineered the custom Capture-the-Flag (CTF) platform, and organized webinars and hands-on workshops engaging 100+ attendees per session.",
    impact: "Engineered custom CTF platform, secured PLDT Innolabs partnership, and engaged 100+ participants per session.",
    image: "/cyberph.JPG",
    imageAlt: "CyberPH Capture-the-Flag competition platform",
    tags: ["Cybersecurity", "CTF Platform", "Cloud Infrastructure", "Strategic Planning"],
  },
  {
    id: "gdg-pup",
    index: "03",
    title: "Google Developer Groups on Campus PUP",
    role: "Cybersecurity Lead",
    period: "Aug. 2024 – Sep. 2025",
    location: "PUP Manila",
    description:
      "Engineered containerized challenge infrastructure (Docker, AWS) supporting a national CTF competition with 100+ participants. Designed and instructed student workshops on modern security practices, DevSecOps, GitHub Actions CI/CD, and OWASP API Security.",
    impact: "Deployed Docker/AWS challenge infrastructure for national CTF and trained 100+ student developers.",
    image: "/gdg-pup.jpg",
    imageAlt: "Google Developer Groups campus workshop",
    tags: ["Docker", "AWS", "DevSecOps", "GitHub Actions", "OWASP"],
  },
  {
    id: "icpep-pup",
    index: "04",
    title: "ICPEP Student Edition - PUP Manila",
    role: "President and Founder",
    period: "Oct. 2024 – Sep. 2025",
    location: "PUP Manila",
    description:
      "Founded and established the university chapter from the ground up, defining organizational governance, core bylaws, and executive structure. Scaled chapter membership to over 200 active student engineers while forging an official strategic partnership with GitHub Education.",
    impact: "Scaled chapter to 200+ members, forged strategic partnership with GitHub Education, and led student hackathons.",
    image: "/icpep.jpg",
    imageAlt: "ICPEP Student Edition PUP Manila chapter leadership",
    tags: ["President & Founder", "GitHub Education", "Student Engineering", "Hackathons"],
  },
  {
    id: "pup-hygears",
    index: "05",
    title: "PUP Hygears",
    role: "Programming Team Leader",
    period: "Oct. 2021 – Sep. 2025",
    location: "Manila / Indonesia",
    description:
      "Directed the programming and electrical sub-teams in engineering telemetry, electronic components, and vehicle control systems for the Shell Eco-marathon Asia competition in Indonesia. Architected a real-time telemetry data pipeline utilizing InfluxDB and built an ambient air quality monitoring dashboard with Flask and React.",
    impact: "Engineered real-time vehicle telemetry pipeline with InfluxDB and live dashboard for international competition.",
    image: "/pup-hygears.JPG",
    imageAlt: "PUP Hygears vehicle telemetry engineering",
    tags: ["Telemetry", "InfluxDB", "Flask & React", "Shell Eco-marathon"],
  },
  {
    id: "dost-start",
    index: "06",
    title: "DOST - START",
    role: "Partnership Lead",
    period: "Jan. 2025 – Sep. 2025",
    location: "Philippines",
    description:
      "Served as Founding Partnership Lead, directing strategic stakeholder engagements and championing institutional collaborations to support youth in STEM. Guided strategic requirements and product roadmap for the organization's public web presence and primary research data collection.",
    impact: "Directed nationwide stakeholder engagements and automated outreach championing youth in STEM.",
    image: "/dost-start.jpg",
    imageAlt: "DOST START STEM outreach summit",
    tags: ["DOST-SEI", "STEM Advocacy", "Strategic Partnerships"],
  },
  {
    id: "microsoft-student-community",
    index: "07",
    title: "PUP Microsoft Student Community",
    role: "PowerBI Lead",
    period: "Aug. 2024 – Sep. 2025",
    location: "PUP Manila",
    description:
      "Spearheaded the technical data track, instructing 50+ students in foundational data gathering, ETL pipelines, and data cleaning best practices. Delivered comprehensive training on business intelligence, data visualization, and dynamic dashboard creation using Microsoft Power BI.",
    impact: "Trained 50+ students in ETL data pipelines and dynamic business intelligence dashboards with Power BI.",
    image: "/microsoft-student-club.jpg",
    imageAlt: "Power BI and data analytics workshop",
    tags: ["Microsoft", "Power BI", "Data Analytics", "ETL Pipelines"],
  },
];

export const SOCIALS: SocialLink[] = [
  {
    label: "Website",
    handle: "mj.erosa.page",
    url: "https://mj.erosa.page",
    description: "Official portfolio and personal website",
  },
  {
    label: "GitHub",
    handle: "github.com/marvinjameserosa",
    url: "https://github.com/marvinjameserosa",
    description: "Open-source repositories, developer tools, and contributions",
  },
  {
    label: "LinkedIn",
    handle: "linkedin.com/in/marvinjameserosa",
    url: "https://linkedin.com/in/marvinjameserosa",
    description: "Professional background, network, and recommendations",
  },
  {
    label: "Email",
    handle: "marvinjameserosa@gmail.com",
    url: "mailto:marvinjameserosa@gmail.com",
    description: "Direct email for speaking, partnerships, and technical roles",
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    id: "arduino-day-ph",
    index: "01",
    title: "Arduino Day Philippines",
    description:
      "Official website for Arduino Day Philippines 2026 — a community-led celebration of Arduino's birthday featuring talks, demos, and maker showcases. Built and launched ahead of the March 21, 2026 event at Asia Pacific College, Makati.",
    role: "Website Lead",
    stack: ["Next.js", "TypeScript", "Tailwind CSS"],
    status: "Live",
    image: "/arduino-day-ph.jpg",
    imageAlt: "Arduino Day Philippines 2026 website screenshot",
    links: [
      { label: "Visit Site", url: "https://www.arduinodayphilippines.cc/" },
    ],
  },
];

export const COMMANDS: CommandDefinition[] = [
  {
    cmd: "talks",
    description: "Keynotes, conference sessions & presentations with photos",
    isQuickAction: true,
  },
  {
    cmd: "projects",
    description: "Side projects, open-source work & things I've shipped",
    isQuickAction: true,
  },
  {
    cmd: "community",
    description: "Community leadership, volunteering & open-source work",
    isQuickAction: true,
  },
  {
    cmd: "socials",
    description: "GitHub, LinkedIn & email links",
    isQuickAction: true,
  },
  {
    cmd: "about",
    description: "Professional background, engineering philosophy & bio",
    isQuickAction: true,
  },
  {
    cmd: "contact",
    description: "Direct reach out and collaboration channels",
  },
  {
    cmd: "help",
    description: "List all supported terminal commands",
  },
  {
    cmd: "clear",
    description: "Wipe previous terminal output and reset session",
  },
];

